package com.batman.k8smybatis.common.dao;

import com.batman.k8smybatis.common.model.Bill;

public interface BillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    int insert(Bill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    int insertSelective(Bill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    Bill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    int updateByPrimaryKeySelective(Bill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    int updateByPrimaryKey(Bill record);
}