package com.batman.k8smybatis.common.model;

import java.math.BigDecimal;
import java.util.Date;

public class Bill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.id
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.file_id
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private Integer fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.claim_id
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private Integer claimId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.serial_no
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private String serialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.claim_serial_no
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private String claimSerialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.bill_no
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private String billNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.bill_type
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private Integer billType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.mergency_type
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private String mergencyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.health_type
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private String healthType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.vip_type
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private String vipType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.treatment_date
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private Date treatmentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.in_hospital_date
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private Date inHospitalDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.out_hospital_date
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private Date outHospitalDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.hospital_code
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private String hospitalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.hospital_name
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private String hospitalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.hospital_dept
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private Integer hospitalDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.hospital_dept_name
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private String hospitalDeptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.match_hospital_code
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private String matchHospitalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.match_hospital_name
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private String matchHospitalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.match_hospital_status
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private Integer matchHospitalStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.diagnose_code
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private String diagnoseCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.diagnose_name
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private String diagnoseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.match_diagnose_code
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private String matchDiagnoseCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.match_diagnose_name
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private String matchDiagnoseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.match_diagnose_status
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private Integer matchDiagnoseStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.bill_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private BigDecimal billAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.bill_status
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private Integer billStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.social_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private BigDecimal socialPayAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.class_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private BigDecimal classPayAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.own_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private BigDecimal ownPayAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.third_party_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private BigDecimal thirdPartyPayAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.is_third_party_pay
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private String isThirdPartyPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.fund_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private BigDecimal fundPayAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.large_fund_hos_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private BigDecimal largeFundHosPayAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.fund_year_total_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private BigDecimal fundYearTotalPayAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.large_fund_out_curr_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private BigDecimal largeFundOutCurrPayAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.large_fund_out_year_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private BigDecimal largeFundOutYearPayAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.bill_user_name
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private String billUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.image_file_no
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private String imageFileNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.image_file_id
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private Integer imageFileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.reason_notes
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private String reasonNotes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.remark
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.delete_flag
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.create_operator
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private Integer createOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.create_time
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.update_operator
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private Integer updateOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.update_time
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.artificial_describe
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private String artificialDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.extra_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private BigDecimal extraPayAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.personal_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private BigDecimal personalPayAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.deductible
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    private BigDecimal deductible;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.id
     *
     * @return the value of bill.id
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.id
     *
     * @param id the value for bill.id
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.file_id
     *
     * @return the value of bill.file_id
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.file_id
     *
     * @param fileId the value for bill.file_id
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.claim_id
     *
     * @return the value of bill.claim_id
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public Integer getClaimId() {
        return claimId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.claim_id
     *
     * @param claimId the value for bill.claim_id
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setClaimId(Integer claimId) {
        this.claimId = claimId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.serial_no
     *
     * @return the value of bill.serial_no
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.serial_no
     *
     * @param serialNo the value for bill.serial_no
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo == null ? null : serialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.claim_serial_no
     *
     * @return the value of bill.claim_serial_no
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public String getClaimSerialNo() {
        return claimSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.claim_serial_no
     *
     * @param claimSerialNo the value for bill.claim_serial_no
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setClaimSerialNo(String claimSerialNo) {
        this.claimSerialNo = claimSerialNo == null ? null : claimSerialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.bill_no
     *
     * @return the value of bill.bill_no
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public String getBillNo() {
        return billNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.bill_no
     *
     * @param billNo the value for bill.bill_no
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setBillNo(String billNo) {
        this.billNo = billNo == null ? null : billNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.bill_type
     *
     * @return the value of bill.bill_type
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public Integer getBillType() {
        return billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.bill_type
     *
     * @param billType the value for bill.bill_type
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setBillType(Integer billType) {
        this.billType = billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.mergency_type
     *
     * @return the value of bill.mergency_type
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public String getMergencyType() {
        return mergencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.mergency_type
     *
     * @param mergencyType the value for bill.mergency_type
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setMergencyType(String mergencyType) {
        this.mergencyType = mergencyType == null ? null : mergencyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.health_type
     *
     * @return the value of bill.health_type
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public String getHealthType() {
        return healthType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.health_type
     *
     * @param healthType the value for bill.health_type
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setHealthType(String healthType) {
        this.healthType = healthType == null ? null : healthType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.vip_type
     *
     * @return the value of bill.vip_type
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public String getVipType() {
        return vipType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.vip_type
     *
     * @param vipType the value for bill.vip_type
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setVipType(String vipType) {
        this.vipType = vipType == null ? null : vipType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.treatment_date
     *
     * @return the value of bill.treatment_date
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public Date getTreatmentDate() {
        return treatmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.treatment_date
     *
     * @param treatmentDate the value for bill.treatment_date
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setTreatmentDate(Date treatmentDate) {
        this.treatmentDate = treatmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.in_hospital_date
     *
     * @return the value of bill.in_hospital_date
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public Date getInHospitalDate() {
        return inHospitalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.in_hospital_date
     *
     * @param inHospitalDate the value for bill.in_hospital_date
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setInHospitalDate(Date inHospitalDate) {
        this.inHospitalDate = inHospitalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.out_hospital_date
     *
     * @return the value of bill.out_hospital_date
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public Date getOutHospitalDate() {
        return outHospitalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.out_hospital_date
     *
     * @param outHospitalDate the value for bill.out_hospital_date
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setOutHospitalDate(Date outHospitalDate) {
        this.outHospitalDate = outHospitalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.hospital_code
     *
     * @return the value of bill.hospital_code
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public String getHospitalCode() {
        return hospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.hospital_code
     *
     * @param hospitalCode the value for bill.hospital_code
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setHospitalCode(String hospitalCode) {
        this.hospitalCode = hospitalCode == null ? null : hospitalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.hospital_name
     *
     * @return the value of bill.hospital_name
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.hospital_name
     *
     * @param hospitalName the value for bill.hospital_name
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName == null ? null : hospitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.hospital_dept
     *
     * @return the value of bill.hospital_dept
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public Integer getHospitalDept() {
        return hospitalDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.hospital_dept
     *
     * @param hospitalDept the value for bill.hospital_dept
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setHospitalDept(Integer hospitalDept) {
        this.hospitalDept = hospitalDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.hospital_dept_name
     *
     * @return the value of bill.hospital_dept_name
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public String getHospitalDeptName() {
        return hospitalDeptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.hospital_dept_name
     *
     * @param hospitalDeptName the value for bill.hospital_dept_name
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setHospitalDeptName(String hospitalDeptName) {
        this.hospitalDeptName = hospitalDeptName == null ? null : hospitalDeptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.match_hospital_code
     *
     * @return the value of bill.match_hospital_code
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public String getMatchHospitalCode() {
        return matchHospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.match_hospital_code
     *
     * @param matchHospitalCode the value for bill.match_hospital_code
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setMatchHospitalCode(String matchHospitalCode) {
        this.matchHospitalCode = matchHospitalCode == null ? null : matchHospitalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.match_hospital_name
     *
     * @return the value of bill.match_hospital_name
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public String getMatchHospitalName() {
        return matchHospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.match_hospital_name
     *
     * @param matchHospitalName the value for bill.match_hospital_name
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setMatchHospitalName(String matchHospitalName) {
        this.matchHospitalName = matchHospitalName == null ? null : matchHospitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.match_hospital_status
     *
     * @return the value of bill.match_hospital_status
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public Integer getMatchHospitalStatus() {
        return matchHospitalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.match_hospital_status
     *
     * @param matchHospitalStatus the value for bill.match_hospital_status
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setMatchHospitalStatus(Integer matchHospitalStatus) {
        this.matchHospitalStatus = matchHospitalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.diagnose_code
     *
     * @return the value of bill.diagnose_code
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public String getDiagnoseCode() {
        return diagnoseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.diagnose_code
     *
     * @param diagnoseCode the value for bill.diagnose_code
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setDiagnoseCode(String diagnoseCode) {
        this.diagnoseCode = diagnoseCode == null ? null : diagnoseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.diagnose_name
     *
     * @return the value of bill.diagnose_name
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public String getDiagnoseName() {
        return diagnoseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.diagnose_name
     *
     * @param diagnoseName the value for bill.diagnose_name
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setDiagnoseName(String diagnoseName) {
        this.diagnoseName = diagnoseName == null ? null : diagnoseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.match_diagnose_code
     *
     * @return the value of bill.match_diagnose_code
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public String getMatchDiagnoseCode() {
        return matchDiagnoseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.match_diagnose_code
     *
     * @param matchDiagnoseCode the value for bill.match_diagnose_code
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setMatchDiagnoseCode(String matchDiagnoseCode) {
        this.matchDiagnoseCode = matchDiagnoseCode == null ? null : matchDiagnoseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.match_diagnose_name
     *
     * @return the value of bill.match_diagnose_name
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public String getMatchDiagnoseName() {
        return matchDiagnoseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.match_diagnose_name
     *
     * @param matchDiagnoseName the value for bill.match_diagnose_name
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setMatchDiagnoseName(String matchDiagnoseName) {
        this.matchDiagnoseName = matchDiagnoseName == null ? null : matchDiagnoseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.match_diagnose_status
     *
     * @return the value of bill.match_diagnose_status
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public Integer getMatchDiagnoseStatus() {
        return matchDiagnoseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.match_diagnose_status
     *
     * @param matchDiagnoseStatus the value for bill.match_diagnose_status
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setMatchDiagnoseStatus(Integer matchDiagnoseStatus) {
        this.matchDiagnoseStatus = matchDiagnoseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.bill_amount
     *
     * @return the value of bill.bill_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public BigDecimal getBillAmount() {
        return billAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.bill_amount
     *
     * @param billAmount the value for bill.bill_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setBillAmount(BigDecimal billAmount) {
        this.billAmount = billAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.bill_status
     *
     * @return the value of bill.bill_status
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public Integer getBillStatus() {
        return billStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.bill_status
     *
     * @param billStatus the value for bill.bill_status
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setBillStatus(Integer billStatus) {
        this.billStatus = billStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.social_pay_amount
     *
     * @return the value of bill.social_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public BigDecimal getSocialPayAmount() {
        return socialPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.social_pay_amount
     *
     * @param socialPayAmount the value for bill.social_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setSocialPayAmount(BigDecimal socialPayAmount) {
        this.socialPayAmount = socialPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.class_pay_amount
     *
     * @return the value of bill.class_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public BigDecimal getClassPayAmount() {
        return classPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.class_pay_amount
     *
     * @param classPayAmount the value for bill.class_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setClassPayAmount(BigDecimal classPayAmount) {
        this.classPayAmount = classPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.own_pay_amount
     *
     * @return the value of bill.own_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public BigDecimal getOwnPayAmount() {
        return ownPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.own_pay_amount
     *
     * @param ownPayAmount the value for bill.own_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setOwnPayAmount(BigDecimal ownPayAmount) {
        this.ownPayAmount = ownPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.third_party_pay_amount
     *
     * @return the value of bill.third_party_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public BigDecimal getThirdPartyPayAmount() {
        return thirdPartyPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.third_party_pay_amount
     *
     * @param thirdPartyPayAmount the value for bill.third_party_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setThirdPartyPayAmount(BigDecimal thirdPartyPayAmount) {
        this.thirdPartyPayAmount = thirdPartyPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.is_third_party_pay
     *
     * @return the value of bill.is_third_party_pay
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public String getIsThirdPartyPay() {
        return isThirdPartyPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.is_third_party_pay
     *
     * @param isThirdPartyPay the value for bill.is_third_party_pay
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setIsThirdPartyPay(String isThirdPartyPay) {
        this.isThirdPartyPay = isThirdPartyPay == null ? null : isThirdPartyPay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.fund_pay_amount
     *
     * @return the value of bill.fund_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public BigDecimal getFundPayAmount() {
        return fundPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.fund_pay_amount
     *
     * @param fundPayAmount the value for bill.fund_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setFundPayAmount(BigDecimal fundPayAmount) {
        this.fundPayAmount = fundPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.large_fund_hos_pay_amount
     *
     * @return the value of bill.large_fund_hos_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public BigDecimal getLargeFundHosPayAmount() {
        return largeFundHosPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.large_fund_hos_pay_amount
     *
     * @param largeFundHosPayAmount the value for bill.large_fund_hos_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setLargeFundHosPayAmount(BigDecimal largeFundHosPayAmount) {
        this.largeFundHosPayAmount = largeFundHosPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.fund_year_total_pay_amount
     *
     * @return the value of bill.fund_year_total_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public BigDecimal getFundYearTotalPayAmount() {
        return fundYearTotalPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.fund_year_total_pay_amount
     *
     * @param fundYearTotalPayAmount the value for bill.fund_year_total_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setFundYearTotalPayAmount(BigDecimal fundYearTotalPayAmount) {
        this.fundYearTotalPayAmount = fundYearTotalPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.large_fund_out_curr_pay_amount
     *
     * @return the value of bill.large_fund_out_curr_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public BigDecimal getLargeFundOutCurrPayAmount() {
        return largeFundOutCurrPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.large_fund_out_curr_pay_amount
     *
     * @param largeFundOutCurrPayAmount the value for bill.large_fund_out_curr_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setLargeFundOutCurrPayAmount(BigDecimal largeFundOutCurrPayAmount) {
        this.largeFundOutCurrPayAmount = largeFundOutCurrPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.large_fund_out_year_pay_amount
     *
     * @return the value of bill.large_fund_out_year_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public BigDecimal getLargeFundOutYearPayAmount() {
        return largeFundOutYearPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.large_fund_out_year_pay_amount
     *
     * @param largeFundOutYearPayAmount the value for bill.large_fund_out_year_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setLargeFundOutYearPayAmount(BigDecimal largeFundOutYearPayAmount) {
        this.largeFundOutYearPayAmount = largeFundOutYearPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.bill_user_name
     *
     * @return the value of bill.bill_user_name
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public String getBillUserName() {
        return billUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.bill_user_name
     *
     * @param billUserName the value for bill.bill_user_name
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setBillUserName(String billUserName) {
        this.billUserName = billUserName == null ? null : billUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.image_file_no
     *
     * @return the value of bill.image_file_no
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public String getImageFileNo() {
        return imageFileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.image_file_no
     *
     * @param imageFileNo the value for bill.image_file_no
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setImageFileNo(String imageFileNo) {
        this.imageFileNo = imageFileNo == null ? null : imageFileNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.image_file_id
     *
     * @return the value of bill.image_file_id
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public Integer getImageFileId() {
        return imageFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.image_file_id
     *
     * @param imageFileId the value for bill.image_file_id
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setImageFileId(Integer imageFileId) {
        this.imageFileId = imageFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.reason_notes
     *
     * @return the value of bill.reason_notes
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public String getReasonNotes() {
        return reasonNotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.reason_notes
     *
     * @param reasonNotes the value for bill.reason_notes
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setReasonNotes(String reasonNotes) {
        this.reasonNotes = reasonNotes == null ? null : reasonNotes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.remark
     *
     * @return the value of bill.remark
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.remark
     *
     * @param remark the value for bill.remark
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.delete_flag
     *
     * @return the value of bill.delete_flag
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.delete_flag
     *
     * @param deleteFlag the value for bill.delete_flag
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.create_operator
     *
     * @return the value of bill.create_operator
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public Integer getCreateOperator() {
        return createOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.create_operator
     *
     * @param createOperator the value for bill.create_operator
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setCreateOperator(Integer createOperator) {
        this.createOperator = createOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.create_time
     *
     * @return the value of bill.create_time
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.create_time
     *
     * @param createTime the value for bill.create_time
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.update_operator
     *
     * @return the value of bill.update_operator
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public Integer getUpdateOperator() {
        return updateOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.update_operator
     *
     * @param updateOperator the value for bill.update_operator
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setUpdateOperator(Integer updateOperator) {
        this.updateOperator = updateOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.update_time
     *
     * @return the value of bill.update_time
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.update_time
     *
     * @param updateTime the value for bill.update_time
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.artificial_describe
     *
     * @return the value of bill.artificial_describe
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public String getArtificialDescribe() {
        return artificialDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.artificial_describe
     *
     * @param artificialDescribe the value for bill.artificial_describe
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setArtificialDescribe(String artificialDescribe) {
        this.artificialDescribe = artificialDescribe == null ? null : artificialDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.extra_pay_amount
     *
     * @return the value of bill.extra_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public BigDecimal getExtraPayAmount() {
        return extraPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.extra_pay_amount
     *
     * @param extraPayAmount the value for bill.extra_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setExtraPayAmount(BigDecimal extraPayAmount) {
        this.extraPayAmount = extraPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.personal_pay_amount
     *
     * @return the value of bill.personal_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public BigDecimal getPersonalPayAmount() {
        return personalPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.personal_pay_amount
     *
     * @param personalPayAmount the value for bill.personal_pay_amount
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setPersonalPayAmount(BigDecimal personalPayAmount) {
        this.personalPayAmount = personalPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.deductible
     *
     * @return the value of bill.deductible
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public BigDecimal getDeductible() {
        return deductible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.deductible
     *
     * @param deductible the value for bill.deductible
     *
     * @mbggenerated Fri Jun 28 11:28:30 CST 2019
     */
    public void setDeductible(BigDecimal deductible) {
        this.deductible = deductible;
    }
}